server:
  port: 8080
spring:
  mvc:
    servlet:
      path: /api
  jackson:
    mapper:
      accept-case-insensitive-properties: true
    serialization:
      write_dates_as_timestamps: false
  datasource:
    url: ${db.url:jdbc:postgresql://127.0.0.1:5432/study_db}
    username: ${db.username:postgres}
    password: ${db.password:restUser}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 60000
      maximum-pool-size: 50
logging:
  file:
    max-history: 20

